// Auto-generated from former i18n/dictionaries/ko.json.
// Korean-only site — no "ko" switching, no dictionary loader.
// Edit Korean strings directly here.
//
// Repeated literal phrases are intentional — they live in different
// nested sections of the dictionary and are surfaced in unrelated UI
// contexts. Extracting them to constants would obscure the structure
// without removing the duplication callers see.
/* eslint-disable sonarjs/no-duplicate-string */

export const STRINGS ={
  "common": {
    "search": "검색",
    "filter": "필터",
    "reset": "초기화",
    "complete": "완료",
    "cancel": "취소",
    "share": "공유하기",
    "report": "신고하기",
    "login": "로그인",
    "logout": "로그아웃",
    "mypage": "마이페이지",
    "loading": "로딩 중...",
    "error": "오류가 발생했습니다",
    "retry": "다시 시도",
    "close": "닫기",
    "save": "저장",
    "saving": "저장 중...",
    "saved": "저장되었습니다",
    "edit": "수정",
    "delete": "삭제",
    "confirm": "확인",
    "back": "뒤로",
    "next": "다음",
    "previous": "이전",
    "seeAll": "전체보기",
    "noData": "데이터가 없습니다",
    "like": "좋아요",
    "unlike": "좋아요 취소",
    "notifications": "알림",
    "goBack": "뒤로 가기",
    "scrollToTop": "상단으로 이동",
    "linkCopied": "링크가 복사되었습니다",
    "reportComingSoon": "신고 기능은 준비 중입니다",
    "free": "무료",
    "all": "전체",
    "seeMore": "더보기",
    "change": "변경",
    "select": "선택",
    "gridView": "그리드 보기",
    "listView": "리스트 보기",
    "previousImage": "이전 이미지",
    "nextImage": "다음 이미지",
    "clearSearch": "검색어 삭제",
    "noSearchResults": "검색 결과가 없습니다",
    "maxAttachments": "최대 {max}개까지만 첨부할 수 있습니다.",
    "imageUploadFailed": "이미지 업로드에 실패했습니다",
    "imageOnlyError": "이미지 파일만 업로드할 수 있습니다.",
    "imageSizeError": "이미지 크기는 10MB 이하여야 합니다.",
    "goHome": "홈으로 돌아가기",
    "submitting": "등록 중...",
    "currencyUnit": "원",
    "distance": "거리",
    "reviews": "리뷰",
    "bodyPart": "부위",
    "resetRegion": "지역 초기화",
    "likeAdded": "관심 목록에 추가했습니다",
    "likeRemoved": "좋아요를 취소했습니다"
  },
  "home": {
    "title": "타투 아티스트",
    "subtitle": "{{count}}명의 아티스트가 활동 중입니다",
    "noResults": "검색 결과가 없습니다",
    "searchPlaceholder": "아티스트, 장르, 지역 검색",
    "popularArtists": "인기 아티스트",
    "recentPortfolios": "최신 포트폴리오"
  },
  "filter": {
    "region": "지역",
    "genre": "장르",
    "subject": "주제",
    "bodyPart": "부위",
    "selectRegion": "지역 선택",
    "allRegions": "전체 지역",
    "selectGenre": "장르 선택",
    "allGenres": "전체 장르",
    "selectSubject": "주제 선택",
    "allSubjects": "전체 주제",
    "selectBodyPart": "부위 선택",
    "allBodyParts": "전체 부위",
    "applyFilter": "필터 적용",
    "resetFilter": "필터 초기화",
    "distance": "거리",
    "within5km": "5km 이내",
    "within10km": "10km 이내",
    "within20km": "20km 이내",
    "noSubRegions": "세부 지역이 없습니다",
    "selectRegionPrompt": "지역을 선택하세요",
    "noRegionData": "지역 정보가 없습니다"
  },
  "artist": {
    "portfolio": "포트폴리오",
    "reviews": "리뷰",
    "booking": "예약하기",
    "likes": "좋아요",
    "views": "조회수",
    "followers": "팔로워",
    "following": "팔로잉",
    "follow": "팔로우",
    "unfollow": "언팔로우",
    "about": "소개",
    "location": "위치",
    "contact": "연락처",
    "sns": "SNS",
    "workingHours": "영업시간",
    "priceRange": "가격대",
    "specialty": "전문 분야",
    "noPortfolio": "포트폴리오가 없습니다",
    "noReviews": "리뷰가 없습니다",
    "startChat": "1:1 대화 시작하기",
    "showMore": "더보기",
    "showLess": "접기",
    "totalCount": "총 {count}개",
    "searchByCondition": "전국 아티스트, 조건별 검색"
  },
  "portfolio": {
    "discountEvent": "할인이벤트",
    "writeReview": "리뷰 작성하기",
    "edit": "수정",
    "delete": "삭제",
    "recommend": "추천",
    "reservation": "구매하기",
    "listType1": "목록타입1",
    "listType2": "목록타입2",
    "total": "총",
    "count": "개",
    "similarDesign": "비슷한 디자인",
    "othersViewed": "다른 고객이 함께 본 디자인",
    "lowerPrice": "내가 본 디자인보다 낮은 가격대",
    "higherPrice": "내가 본 디자인보다 높은 가격대",
    "samePart": "같은 부위 추천 디자인",
    "recommended": "이런 스타일은 어때요?",
    "noDescription": "상세 설명이 없습니다.",
    "noReservationLink": "예약 링크가 없습니다",
    "reservationCreated": "예약이 생성되었습니다"
  },
  "regions": {
    "seoul": "서울",
    "gyeonggi": "경기",
    "incheon": "인천",
    "daejeon": "대전",
    "sejong": "세종",
    "chungnam": "충남",
    "chungbuk": "충북",
    "gangwon": "강원",
    "busan": "부산",
    "daegu": "대구",
    "ulsan": "울산",
    "gyeongnam": "경남",
    "gyeongbuk": "경북",
    "gwangju": "광주",
    "jeonnam": "전남",
    "jeonbuk": "전북",
    "jeju": "제주"
  },
  "genres": {
    "blackAndGray": "블랙앤그레이",
    "watercolor": "수채화",
    "lettering": "레터링",
    "oriental": "동양화",
    "newSchool": "뉴스쿨",
    "oldSchool": "올드스쿨",
    "realistic": "리얼리스틱",
    "tribal": "트라이벌",
    "geometric": "지오메트릭",
    "minimalist": "미니멀",
    "coverUp": "커버업",
    "dotwork": "닷워크"
  },
  "bodyParts": {
    "arm": "팔",
    "leg": "다리",
    "back": "등",
    "chest": "가슴",
    "hand": "손",
    "foot": "발",
    "neck": "목",
    "head": "머리",
    "shoulder": "어깨",
    "waist": "허리",
    "finger": "손가락",
    "wrist": "손목"
  },
  "auth": {
    "loginTitle": "로그인",
    "signupTitle": "회원가입",
    "email": "이메일",
    "emailOrUsername": "이메일 또는 아이디",
    "username": "아이디",
    "password": "비밀번호",
    "confirmPassword": "비밀번호 확인",
    "forgotPassword": "비밀번호 찾기",
    "rememberMe": "로그인 상태 유지",
    "loginWithKakao": "카카오로 로그인",
    "loginWithGoogle": "구글로 로그인",
    "loginWithApple": "애플로 로그인",
    "loginWithEmail": "이메일로 로그인",
    "loginWithId": "아이디로 로그인",
    "loginWithSns": "SNS로 로그인",
    "noAccount": "계정이 없으신가요?",
    "hasAccount": "이미 계정이 있으신가요?",
    "signupNow": "회원가입",
    "loginNow": "로그인하기",
    "nickname": "닉네임",
    "nicknameOptional": "닉네임 (선택)",
    "contact": "연락처",
    "usernameRule": "영문자로 시작, 4-12자",
    "passwordRule": "영문+숫자 조합, 6자 이상",
    "passwordMinLength": "6자 이상 입력",
    "passwordMismatch": "비밀번호가 일치하지 않습니다",
    "passwordMinError": "비밀번호는 6자 이상이어야 합니다",
    "signupSuccess": "회원가입이 완료되었습니다",
    "signupEmailSent": "가입 확인 이메일을 보냈습니다",
    "checkEmailToComplete": "이메일을 확인하여 가입을 완료해주세요",
    "backToLogin": "로그인으로 돌아가기",
    "resetEmailSent": "비밀번호 재설정 이메일을 보냈습니다",
    "checkEmailToReset": "이메일을 확인하여 비밀번호를 재설정해주세요",
    "newPassword": "새 비밀번호",
    "enterNewPassword": "새로운 비밀번호를 입력해주세요",
    "changePassword": "비밀번호 변경",
    "passwordChanged": "비밀번호가 변경되었습니다",
    "sendResetEmail": "재설정 이메일 보내기",
    "resetDescription": "가입한 이메일을 입력하시면 비밀번호 재설정 링크를 보내드립니다",
    "step1Title": "약관 동의",
    "step2Title": "정보 입력",
    "step3Title": "가입 완료",
    "termsAgreement": "약관 동의",
    "agreeAll": "전체 동의",
    "agreeAllDesc": "아래의 약관에 모두 동의합니다.",
    "privacyPolicy": "개인정보처리방침",
    "privacyPolicyAgree": "개인정보처리방침에 동의합니다.",
    "privacyPolicyRequired": "(필수)",
    "termsOfService": "이용약관",
    "termsOfServiceAgree": "이용약관에 동의합니다.",
    "termsOfServiceRequired": "(필수)",
    "locationService": "위치기반서비스이용약관",
    "locationServiceAgree": "위치기반서비스이용약관에 동의합니다.",
    "locationServiceRequired": "(필수)",
    "viewTerms": "전문보기",
    "mustAgreeAll": "모든 필수 약관에 동의해주세요.",
    "profileImage": "프로필 이미지",
    "profileImageRequired": "(필수)",
    "profileImageHint": "프로필 이미지를 등록해주세요.",
    "selectImage": "이미지 선택",
    "changeImage": "이미지 변경",
    "welcomeMessage": "회원가입을 축하합니다!",
    "welcomeDesc": "반언니에 오신 것을 환영합니다.",
    "startService": "서비스 시작하기",
    "signupFailed": "회원가입에 실패했습니다",
    "signupError": "회원가입 중 오류가 발생했습니다",
    "welcomePersonalized": "{username}님, 반언니에 오신 것을 환영합니다."
  },
  "mypage": {
    "profile": "프로필",
    "reservations": "예약 내역",
    "likedArtists": "관심 아티스트",
    "likedPortfolios": "관심작품",
    "settings": "설정",
    "notifications": "알림 설정",
    "language": "언어 설정",
    "theme": "테마 설정",
    "account": "계정 관리",
    "deleteAccount": "계정 삭제",
    "editProfile": "회원정보 수정",
    "artistRegister": "아티스트 등록",
    "viewMyShop": "내 샵 보기",
    "editArtistProfile": "아티스트 정보 수정",
    "dashboard": "대시보드",
    "portfolioManage": "작품등록",
    "courseManage": "수강관리",
    "adManage": "광고 관리",
    "adPurchase": "광고 구매",
    "pointManage": "포인트 관리",
    "reservationHistory": "예약내역조회",
    "messages": "메세지",
    "estimate": "맞춤견적",
    "estimateRequest": "맞춤견적 요청",
    "findModel": "모델구하기",
    "myRecruitments": "내 모델 모집글",
    "myApplications": "내 모델 지원서",
    "community": "커뮤니티",
    "likedPosts": "내가 좋아한 글",
    "myPosts": "내가 쓴 글",
    "myReviews": "나의 리뷰",
    "inquiries": "건의사항",
    "more": "더보기",
    "username": "아이디",
    "usernameReadonly": "아이디는 변경할 수 없습니다.",
    "nickname": "닉네임",
    "nicknamePlaceholder": "닉네임을 입력해주세요",
    "profileImage": "프로필 이미지",
    "password": "비밀번호",
    "passwordPlaceholder": "변경 시에만 입력해주세요",
    "passwordHint": "비밀번호는 6자리 이상이어야 합니다.",
    "passwordConfirm": "비밀번호 확인",
    "passwordConfirmPlaceholder": "비밀번호를 다시 한번 입력해주세요",
    "emailAddress": "이메일 주소",
    "emailPlaceholder": "이메일을 입력해주세요",
    "contact": "연락처",
    "contactPlaceholder": "연락처를 입력해주세요",
    "chatNotification": "채팅 알림 받기",
    "languageSetting": "언어 설정",
    "withdraw": "회원탈퇴",
    "withdrawConfirm": "정말로 탈퇴하시겠습니까?",
    "withdrawArtistWarning": "아티스트 정보 및 포트폴리오 데이터도 함께 삭제됩니다.",
    "withdrawSuccess": "성공적으로 탈퇴되었습니다.",
    "withdrawThanks": "반언니를 이용해주셔서 감사합니다.",
    "save": "저장",
    "saved": "회원정보가 수정되었습니다.",
    "languageChanged": "언어가 변경되었습니다.",
    "salesManagement": "판매관리",
    "availableWithdrawal": "출금 가능 금액",
    "totalSales": "누적 판매금액",
    "totalSettled": "누적 정산금액",
    "unsettledAmount": "정산 예정금액",
    "pendingWithdrawal": "출금 대기중",
    "completedWithdrawal": "출금 완료",
    "settlementHistory": "정산 내역",
    "withdrawalHistory": "출금 내역",
    "requestWithdrawal": "출금 요청",
    "period": "기간",
    "amount": "금액",
    "fee": "수수료",
    "netAmount": "정산금액",
    "status": "상태",
    "bankName": "은행명",
    "enterAmount": "출금 금액을 입력하세요",
    "completed": "완료",
    "pending": "대기",
    "rejected": "거절",
    "reserved": "예약완료",
    "paid": "결제완료",
    "cancelled": "취소",
    "refunded": "환불",
    "pay": "결제하기",
    "cancelReservation": "예약취소",
    "refund": "환불하기"
  },
  "nav": {
    "home": "홈",
    "womenBeauty": "여성 반영구",
    "mensBeauty": "남성 반영구",
    "community": "커뮤니티",
    "exhibition": "기획전",
    "search": "검색",
    "likes": "좋아요",
    "quoteRequest": "견적요청",
    "mypage": "MY"
  },
  "homepage": {
    "tattoo": "타투",
    "piercing": "반영구",
    "popularArtists": "내 고민을 해결할 인기 아티스트",
    "reviewedArtists": "후기가 많은 아티스트 추천",
    "discountedWorks": "할인율이 가장 높은 작품",
    "lowestPrice": "최저가 작품",
    "popularArtistsPreview": "인기 아티스트",
    "recommendedWorks": "추천작품",
    "popularWorks": "인기 작품",
    "modelRecruitment": "모델 모집",
    "seeMore": "더보기",
    "noRecruitment": "모집 중인 모델이 없습니다",
    "searchRegion": "지역을 검색해보세요.",
    "searchGenre": "장르를 검색해보세요.",
    "trendingNow": "요즘 트렌드",
    "indieDesign": "헤어져도 쿨한 독립적 디자인",
    "butlerSection": "상전님 모시는 집사의 처절한 혈서",
    "todayActiveArtists": "오늘의 인기 아티스트",
    "popularTattoo": "인기 타투 작품",
    "eyebrowSection": "첫인상의 완성은 눈썹",
    "touchupSection": "지우고 싶은 과거 터치업의 마법",
    "semiPermanentRecommended": "반영구 추천",
    "aiBannerHeadline": "FREE 눈썹 시뮬레이션",
    "aiBannerDesc": "시술 전 미리보기 — 내 얼굴에 맞는 눈썹 찾기",
    "aiBannerPhoto": "사진 업로드",
    "aiBannerText": "바로 체험",
    "aiBannerCta": "눈썹 시뮬레이션 시작하기",
    "quoteRequestTitle": "견적 요청",
    "quoteRequestDesc": "아티스트들의 견적을 비교하고 선택하세요",
    "quoteRequestBadge": "역경매",
    "modelRecruitTitle": "모델 모집",
    "modelRecruitDesc": "아티스트의 작품 모델이 되어보세요",
    "modelRecruitBadge": "무료시술",
    "exhibition": "기획전",
    "lipSection": "쌩얼 자신감 UP",
    "mensEyebrowSection": "남자의 변신은 무죄",
    "timeSaleSection": "타임세일",
    "tattooGenres": "반영구 장르별 인기 작품",
    "allGenre": "전체"
  },
  "quickMenu": {
    "womenBeauty": "여성 반영구",
    "mensBeauty": "남성 반영구",
    "exhibition": "기획전",
    "artistSearch": "아티스트 검색",
    "discount": "할인",
    "artistInsight": "아티스트 분석",
    "course": "수강",
    "community": "커뮤니티",
    "blog": "블로그"
  },
  "portfolioSearch": {
    "totalCount": "총 {count}개",
    "noResults": "검색 결과가 없습니다",
    "searchPlaceholder": "검색어를 입력하세요",
    "regionView": "지역별 보기",
    "popularInfo": "인기 추천 정보",
    "resetAll": "전체 초기화",
    "allRegions": "전체 지역",
    "search": "검색",
    "back": "뒤로",
    "close": "닫기",
    "resetRegion": "지역 초기화",
    "price": "가격",
    "priceUnlimited": "가격 무제한",
    "priceUnder": "이하",
    "categoryTabs": {
      "GENRE": "장르",
      "SUBJECT": "주제",
      "PART": "부위",
      "SHOP": "부가정보"
    },
    "sortLabels": {
      "popular": "인기순",
      "price_asc": "가격낮은순",
      "price_desc": "가격높은순",
      "newest": "최신순",
      "discount": "할인율순"
    }
  },
  "footer": {
    "about": "반언니 소개",
    "terms": "이용약관",
    "privacy": "개인정보처리방침",
    "contact": "고객센터",
    "partnership": "제휴문의",
    "copyright": "© 2024 반언니. All rights reserved.",
    "companyName": "상호명: (주)플랫폼몬스터 | 사업자등록번호: 363-06-01936 | 통신판매업신고: 제 2022-경기광명-1283호",
    "companyAddress": "주소: 서울시 마포구 월드컵로 81 3층 | 대표자명 : 배미미",
    "companyContact": "고객센터: 010-8699-6664 | howtattoo@howtattoo.com (주말 및 공휴일 휴무 / 오전 10시 ~ 오후 7시)",
    "companyRefund": "(주)플랫폼몬스터에서 결제된 예약금 환불 관련한 의무 및 책임은 저희 플랫폼몬스터에 있습니다.",
    "companyResponsibility": "반언니에서 상품, 상품정보, 거래, 예약에 관한 의무와 책임은 반언니에게 있습니다.",
    "companyComplaint": "민원담당자 김대성 / 연락처 010-8699-6664"
  },
  "error": {
    "notFound": "페이지를 찾을 수 없습니다",
    "serverError": "서버 오류가 발생했습니다",
    "networkError": "네트워크 연결을 확인해주세요",
    "unauthorized": "로그인이 필요합니다",
    "forbidden": "접근 권한이 없습니다"
  },
  "theme": {
    "toggle": "테마 전환",
    "light": "라이트 모드",
    "dark": "다크 모드",
    "system": "시스템 설정"
  },
  "pages": {
    "home": "홈",
    "homeDesc": "반언니에 오신 것을 환영합니다",
    "tattooSearch": "타투 검색",
    "tattooSearchDesc": "전국 타투 작품을 검색하세요",
    "artistsList": "아티스트",
    "artistsListDesc": "전국 타투이스트를 검색하세요",
    "portfoliosList": "포트폴리오",
    "portfoliosListDesc": "다양한 타투 작품을 확인하세요",
    "discount": "할인",
    "discountDesc": "할인 중인 포트폴리오를 모아보세요",
    "recruitment": "모델 모집",
    "recruitmentDesc": "타투 모델 모집 중인 아티스트를 확인하세요",
    "about": "반언니 소개",
    "aboutDesc": "타투 아티스트 검색 플랫폼 반언니를 소개합니다",
    "aboutContent": "반언니는 전국 타투 아티스트를 연결하는 플랫폼입니다. 고객에게 최적의 타투이스트를 찾아드리고, 아티스트에게는 더 많은 고객을 만날 수 있는 기회를 제공합니다.",
    "terms": "이용약관",
    "termsContent": "본 약관은 주식회사 플랫폼몬스터(이하 \"회사\")가 운영하는 반언니 서비스(이하 \"서비스\")의 이용에 관한 조건 및 절차, 기타 필요한 사항을 규정함을 목적으로 합니다.\n\n제1조 (목적)\n본 약관은 회사가 제공하는 서비스의 이용조건 및 절차에 관한 기본적인 사항을 규정하는 것을 목적으로 합니다.\n\n제2조 (용어의 정의)\n1. \"서비스\"란 회사가 운영하는 반언니 플랫폼을 통해 제공하는 모든 서비스를 의미합니다.\n2. \"이용자\"란 이 약관에 따라 서비스를 이용하는 회원 및 비회원을 말합니다.\n3. \"회원\"이란 서비스에 회원등록을 하고 서비스를 이용하는 자를 말합니다.\n\n제3조 (약관의 효력 및 변경)\n1. 본 약관은 서비스를 이용하고자 하는 모든 이용자에게 그 효력이 발생합니다.\n2. 회사는 합리적인 사유가 발생한 경우 관련 법령에 위배되지 않는 범위 내에서 약관을 변경할 수 있습니다.\n\n제4조 (서비스의 제공)\n1. 회사는 다음과 같은 서비스를 제공합니다.\n   - 타투 아티스트 검색 및 포트폴리오 열람\n   - 아티스트와 고객 간 예약 중개\n   - 리뷰 및 평점 서비스\n   - 기타 회사가 정하는 서비스",
    "privacy": "개인정보처리방침",
    "privacyContent": "주식회사 플랫폼몬스터(이하 \"회사\")는 정보통신망 이용촉진 및 정보보호 등에 관한 법률, 개인정보보호법 등 관련 법령에 따라 이용자의 개인정보를 보호하고 있습니다.\n\n1. 수집하는 개인정보 항목\n- 필수항목: 이메일, 비밀번호, 닉네임\n- 선택항목: 프로필 사진, 연락처\n- 서비스 이용 시 자동 수집: 접속 IP, 접속 일시, 서비스 이용 기록\n\n2. 개인정보의 수집 및 이용 목적\n- 서비스 제공 및 운영\n- 회원 관리 및 본인 확인\n- 서비스 개선 및 신규 서비스 개발\n- 마케팅 및 광고 활용 (동의 시)\n\n3. 개인정보의 보유 및 이용기간\n- 회원 탈퇴 시까지 (관련 법령에 따라 일정 기간 보존이 필요한 경우 해당 기간까지)\n- 전자상거래법에 따른 보존: 계약/청약철회 기록 5년, 대금결제 기록 5년, 소비자불만 기록 3년\n\n4. 개인정보의 제3자 제공\n- 회사는 이용자의 동의 없이 개인정보를 제3자에게 제공하지 않습니다.\n- 단, 법령에 의한 경우는 예외로 합니다.\n\n5. 개인정보 보호책임자\n- 성명: 김대성\n- 연락처: 010-8699-6664\n- 이메일: howtattoo@howtattoo.com",
    "contact": "고객센터",
    "contactDesc": "문의사항이 있으시면 연락해주세요",
    "contactPhone": "전화: 010-8699-6664",
    "contactEmail": "이메일: howtattoo@howtattoo.com",
    "contactHours": "운영시간: 평일 오전 10시 ~ 오후 7시 (주말 및 공휴일 휴무)",
    "partnership": "제휴문의",
    "partnershipDesc": "반언니와 함께할 파트너를 찾고 있습니다",
    "partnershipContent": "타투 샵, 반영구 샵, 피어싱 샵 등 뷰티 업종 파트너십을 환영합니다. 제휴 문의는 아래 연락처로 부탁드립니다.",
    "comingSoon": "서비스 준비 중입니다",
    "comingSoonDesc": "더 나은 서비스로 찾아뵙겠습니다",
    "semiPermanent": "반영구",
    "semiPermanentDesc": "반영구 시술 서비스를 찾아보세요",
    "womenBeauty": "여성 반영구",
    "womenBeautyDesc": "여성을 위한 반영구 시술 서비스",
    "mensBeauty": "남성 반영구",
    "mensBeautyDesc": "남성을 위한 반영구 시술 서비스",
    "exhibition": "기획전",
    "exhibitionDesc": "특별 기획전 모아보기",
    "quoteRequest": "견적 요청",
    "quoteRequestDesc": "원하는 타투를 설명하고 아티스트들의 견적을 받아보세요",
    "courseDetail": "수강 상세",
    "courseDetailDesc": "타투 수강 상세 정보"
  },
  "quoteRequest": {
    "title": "견적 요청",
    "listTitle": "견적 요청 목록",
    "createNew": "견적 요청하기",
    "myRequests": "내 견적 요청",
    "noRequests": "등록된 견적 요청이 없습니다",
    "bodyPart": "시술 부위",
    "size": "크기",
    "style": "스타일",
    "budget": "예산",
    "budgetMin": "최소 예산",
    "budgetMax": "최대 예산",
    "budgetUnit": "원",
    "description": "상세 설명",
    "descriptionPlaceholder": "원하는 타투에 대해 자세히 설명해주세요",
    "referenceImages": "참고 이미지",
    "referenceImagesDesc": "원하는 스타일의 참고 이미지를 첨부해주세요 (최대 5장)",
    "submit": "견적 요청 등록",
    "statusOpen": "모집중",
    "statusClosed": "마감",
    "statusCompleted": "완료",
    "statusCancelled": "취소",
    "bidCount": "견적 {count}건",
    "noBids": "아직 제출된 견적이 없습니다",
    "submitBid": "견적 제출",
    "price": "시술 가격",
    "estimatedDuration": "예상 소요시간",
    "bidDescription": "견적 설명",
    "bidDescriptionPlaceholder": "시술 방법, 횟수, 포함 사항 등을 설명해주세요",
    "selectArtist": "이 아티스트 선택",
    "selectedArtist": "선택된 아티스트",
    "chatWithArtist": "채팅하기",
    "bidAccepted": "견적이 선택되었습니다",
    "cancel": "취소",
    "close": "마감",
    "sizeSmall": "소 (5cm 이하)",
    "sizeMedium": "중 (5~15cm)",
    "sizeLarge": "대 (15~30cm)",
    "sizeXLarge": "특대 (30cm 이상)",
    "loginRequired": "로그인 후 이용해주세요",
    "artistOnly": "아티스트만 견적을 제출할 수 있습니다",
    "alreadyBid": "이미 견적을 제출했습니다",
    "bidSuccess": "견적이 제출되었습니다",
    "createSuccess": "견적 요청이 등록되었습니다",
    "bodyPartArm": "팔",
    "bodyPartLeg": "다리",
    "bodyPartBack": "등",
    "bodyPartChest": "가슴",
    "bodyPartShoulder": "어깨",
    "bodyPartWrist": "손목",
    "bodyPartAnkle": "발목",
    "bodyPartNeck": "목",
    "bodyPartRib": "옆구리",
    "bodyPartThigh": "허벅지",
    "bodyPartOther": "기타",
    "stylePlaceholder": "레터링, 이레즈미, 블랙앤그레이...",
    "goBack": "뒤로가기",
    "removeImage": "이미지 삭제",
    "edit": "수정",
    "delete": "삭제",
    "deleteConfirm": "이 견적 요청을 삭제하시겠습니까?",
    "deleteSuccess": "견적 요청이 삭제되었습니다",
    "editTitle": "견적 요청 수정",
    "update": "수정 완료"
  },
  "recruitment": {
    "listTitle": "모델 모집",
    "createNew": "모델 모집하기",
    "noRecruitments": "모집 중인 모델이 없습니다",
    "title": "제목",
    "titlePlaceholder": "모집 제목을 입력해주세요",
    "bodyPart": "시술 부위",
    "expense": "모델비",
    "expenseFree": "무료 시술",
    "expensePaid": "모델비 지급",
    "condition": "모집 조건",
    "conditionPlaceholder": "성별, 나이, 기타 조건을 입력해주세요",
    "closedAt": "모집 마감일",
    "description": "상세 설명",
    "descriptionPlaceholder": "시술 내용, 소요시간, 장소 등을 설명해주세요",
    "submit": "모집 등록",
    "apply": "모델 지원하기",
    "applied": "지원 완료",
    "deadline": "마감",
    "free": "무료",
    "createSuccess": "모델 모집이 등록되었습니다",
    "loginRequired": "로그인 후 이용해주세요",
    "artistOnly": "아티스트만 모집글을 작성할 수 있습니다",
    "dDay": "D-{days}",
    "bodyPartArm": "팔",
    "bodyPartLeg": "다리",
    "bodyPartBack": "등",
    "bodyPartChest": "가슴",
    "bodyPartShoulder": "어깨",
    "bodyPartWrist": "손목",
    "bodyPartAnkle": "발목",
    "bodyPartNeck": "목",
    "bodyPartRib": "옆구리",
    "bodyPartThigh": "허벅지",
    "bodyPartOther": "기타",
    "goBack": "뒤로가기",
    "edit": "수정",
    "delete": "삭제",
    "deleteConfirm": "이 모집글을 삭제하시겠습니까?",
    "deleteSuccess": "모집글이 삭제되었습니다",
    "updateSuccess": "모집글이 수정되었습니다",
    "contact": "연락처",
    "kakaoChat": "카카오톡 문의",
    "instagram": "인스타그램",
    "artistInfo": "아티스트 정보"
  },
  "seo": {
    "homeTitle": "타투 아티스트 검색 플랫폼",
    "homeDescription": "전국 타투 아티스트를 검색하고 포트폴리오를 확인하세요. 지역별, 장르별 검색으로 나에게 맞는 타투이스트를 찾아보세요.",
    "searchTitle": "타투 아티스트 검색",
    "searchDescription": "지역, 장르, 스타일별로 타투 아티스트를 검색하세요."
  },
  "artistRegister": {
    "title": "아티스트 등록",
    "type": "유형",
    "typeTattoo": "타투",
    "typeSemiPermanent": "반영구",
    "artistName": "아티스트 명",
    "artistNamePlaceholder": "아티스트 명을 입력해주세요",
    "sex": "성별",
    "sexMale": "남성",
    "sexFemale": "여성",
    "sexOther": "기타",
    "phone": "전화번호",
    "phonePlaceholder": "하이픈(-)을 제거한 값을 입력해주세요",
    "instagramUrl": "인스타그램 링크(URL)",
    "instagramUrlPlaceholder": "인스타그램 주소를 입력해주세요",
    "kakaoUrl": "카카오주소 링크(URL)",
    "kakaoUrlPlaceholder": "카카오링크 주소를 입력해주세요",
    "kakaoUrlHint": "인스타 입력시 상담 불가합니다.\n카카오 링크 주소를 입력해 주세요.",
    "address": "주소",
    "zipcode": "우편번호",
    "addressSearch": "검색",
    "addressPlaceholder": "주소",
    "addressDetail": "상세주소",
    "addressDetailPlaceholder": "상세주소",
    "region": "지역",
    "regionSelect": "지역 카테고리 선택",
    "shopImages": "지점 이미지",
    "shopImagesHint": "샵 관련 이미지를 첨부해주세요.",
    "profileImage": "대표 이미지",
    "profileImageHint": "샵 로고 및 시그니처 사진 또는 본인 사진을 올려주세요.",
    "introduce": "목록용 한줄 소개",
    "introducePlaceholder": "소개글을 입력해주세요",
    "description": "본인 소개글",
    "descriptionPlaceholder": "건전한 커뮤니티 문화를 해치는 게시글은 숨김 및 삭제될 수 있습니다.",
    "genre": "장르",
    "genreMultiple": "복수선택 가능",
    "shopInfo": "샵정보",
    "bankHolder": "예금주",
    "bankHolderPlaceholder": "예금주명을 입력해주세요",
    "bankName": "은행명",
    "bankNamePlaceholder": "은행을 선택해주세요",
    "bankAccount": "계좌번호",
    "bankAccountPlaceholder": "계좌번호를 입력해주세요 (숫자만 입력)",
    "submit": "신규등록",
    "submitSuccess": "신규 등록이 완료되었습니다.",
    "alreadyArtist": "이미 아티스트로 등록된 사용자입니다.",
    "required": "필수 항목입니다",
    "selectImage": "선택",
    "changeImage": "변경"
  },
  "review": {
    "rating": "별점",
    "content": "내용",
    "contentPlaceholder": "친절하신가요? 시설은 어떤가요?",
    "photoAttachment": "사진 첨부",
    "photoUploadComingSoon": "사진 업로드 기능 준비중",
    "submitReview": "리뷰 등록하기",
    "reviewSubmitted": "리뷰가 등록되었습니다",
    "writeReview": "리뷰 작성",
    "shareExperience": "시술 경험을 공유해주세요.",
    "invalidAccess": "잘못된 접근입니다. 아티스트 정보가 없습니다.",
    "pageTitle": "리뷰 작성",
    "pageDescription": "타투 시술 리뷰를 작성해주세요."
  },
  "genreData": {
    "genreTitle": "장르",
    "genreItems": "치카노,이레즈미,폴리네시안,감성타투,미니타투,수채화,일러스트,리얼리스틱,레터링,트라이벌,블랙워크,올드스쿨,뉴스쿨,블랙앤그레이,라인워크,커버업,기타",
    "subjectTitle": "주제",
    "subjectItems": "꽃,장미,고래,맹수,나침반,만다라,한야,해골,뱀,용,잉어,동양철학,인물,다크,커플,가족,반려동물,동물,기타",
    "partTitle": "부위",
    "partItems": "목,귀,배,팔,종아리,발,다리,손등,손목,발목,아랫팔,허벅지,가슴,어깨,쇄골,옆구리,무릎,머리,얼굴,등판,엉덩이,두피,팔꿈치,손가락,긴팔,윗팔"
  },
  "exhibition": {
    "submitPortfolio": "작품 출품하기",
    "selectPortfolio": "출품할 작품 선택",
    "submitted": "출품 완료",
    "pending": "심사 중",
    "approved": "승인됨",
    "rejected": "반려됨",
    "withdraw": "출품 취소",
    "noEntries": "아직 출품된 작품이 없습니다",
    "rejectReason": "거절 사유",
    "entryCount": "참여 작품",
    "submitSuccess": "출품이 완료되었습니다",
    "alreadySubmitted": "이미 출품한 작품입니다",
    "exhibitionEnded": "종료된 기획전입니다",
    "selectToSubmit": "출품할 작품을 선택하세요",
    "myEntries": "내 출품 현황",
    "portfolioCount": "개 작품"
  },
  "aiStudio": {
    "comingSoonDesc": "곧 출시됩니다! AI가 당신만의 유니크한 타투 디자인을 생성해 드립니다. 아이디어만 설명하면, 그림 실력이 없어도 됩니다.",
    "feature1": "텍스트로 타투 디자인 생성",
    "feature2": "다양한 스타일 선택 (미니멀, 트라이벌, 수채화 등)",
    "feature3": "크기와 배치 시뮬레이션",
    "feature4": "디자인 저장 및 아티스트 공유",
    "title": "AI 타투 스튜디오",
    "tabGenerate": "디자인 생성",
    "tabTryon": "가상 착용",
    "promptPlaceholder": "원하는 타투를 설명하세요 (예: 장미 타투, 미니멀 스타일)",
    "styleLabel": "스타일",
    "generateBtn": "타투 생성",
    "generating": "생성 중...",
    "tryonTitle": "내 몸에 타투 입혀보기",
    "tryonDesc": "신체 사진을 업로드하고, 타투 디자인을 선택하면 실제로 새긴 것처럼 합성해 드립니다.",
    "uploadBody": "신체 사진 업로드",
    "uploadTattoo": "타투 디자인 업로드",
    "clickToMask": "타투를 배치할 부위를 클릭하세요",
    "applyTattoo": "타투 합성하기",
    "applying": "합성 중...",
    "downloadResult": "결과 다운로드",
    "newDesign": "새 디자인",
    "styles": {
      "minimal": "미니멀",
      "blackwork": "블랙워크",
      "watercolor": "수채화",
      "traditional": "올드스쿨",
      "realism": "리얼리즘",
      "japanese": "일본식",
      "geometric": "기하학",
      "dotwork": "도트워크"
    }
  },
  "globalSearch": {
    "headerSearchPlaceholder": "포트폴리오, 아티스트 검색",
    "searchResults": "검색 결과",
    "portfolioResults": "포트폴리오",
    "artistResults": "아티스트",
    "noSearchResults": "검색 결과가 없습니다",
    "searchAll": "전체 검색",
    "adLabel": "광고"
  },
  "community": {
    "title": "커뮤니티",
    "tattoo": "타투",
    "beauty": "반영구",
    "qna": "QNA",
    "freeTalk": "자유수다",
    "review": "후기",
    "recruitment": "모델모집",
    "recommended": "추천글",
    "latest": "최신글",
    "popular": "인기글",
    "writePost": "글쓰기",
    "noPosts": "게시글이 없습니다",
    "views": "조회",
    "likes": "좋아요",
    "comments": "댓글",
    "writeComment": "댓글을 입력해주세요",
    "submitComment": "등록",
    "deleteConfirm": "정말 삭제하시겠습니까?",
    "loginRequired": "로그인 후 이용해주세요",
    "postTitle": "제목",
    "postTitlePlaceholder": "제목을 입력해주세요",
    "postContent": "내용",
    "postContentPlaceholder": "내용을 입력해주세요",
    "selectCategory": "카테고리를 선택해주세요",
    "submit": "등록",
    "edit": "수정",
    "delete": "삭제",
    "reply": "답글",
    "allPosts": "전체",
    "anonymous": "익명"
  },
  "courseDetail": {
    "highlights": "특장점",
    "curriculum": "커리큘럼",
    "reviews": "수강 후기",
    "artistInfo": "아티스트 정보",
    "location": "위치",
    "duration": "기간",
    "classType": "수업 유형",
    "category": "카테고리",
    "pricePerMonth": "월",
    "tenThousandWon": "만원",
    "originalPrice": "정가",
    "discountApplied": "할인 적용",
    "satisfaction": "만족도",
    "cleanliness": "청결도",
    "kindness": "친절도",
    "chapter": "Chapter",
    "noReviews": "아직 후기가 없습니다",
    "inquire": "수강 문의하기",
    "viewInstagram": "인스타그램 보기",
    "courseList": "수강",
    "courseListDesc": "타투 수강 프로그램을 찾아보세요",
    "heroTitle": "베테랑 타투이스트들의\n타투 수강 모아보기!",
    "heroSubtitle": "현업 타투이스트와 함께 하는 타투 집중 교육,\n준비 되셨나요?",
    "allCategories": "전체",
    "comprehensive": "종합반",
    "machineTechnique": "머신 테크닉",
    "drawing": "드로잉",
    "filterSubtitle": "전국 수강 정보, 조건별 검색!",
    "totalCount": "전체 {count}",
    "noCourses": "등록된 수강 정보가 없습니다"
  }
} as const;
