// AUTO-GENERATED by scripts-temp/generate-topics.mjs
// 365 SEO-targeted Korean tattoo encyclopedia topics. Do not edit manually.
// Re-run the script if you need to add/replace entries.

export interface EncyclopediaTopic {
  id: number;
  category: string;
  title: string;
  keyword: string;
}

export const ENCYCLOPEDIA_TOPICS: readonly EncyclopediaTopic[] = [
  {
    "id": 1,
    "category": "스타일",
    "title": "미니타투",
    "keyword": "미니타투"
  },
  {
    "id": 2,
    "category": "스타일",
    "title": "레터링타투",
    "keyword": "레터링타투"
  },
  {
    "id": 3,
    "category": "스타일",
    "title": "이레즈미",
    "keyword": "이레즈미"
  },
  {
    "id": 4,
    "category": "스타일",
    "title": "트라이벌",
    "keyword": "트라이벌"
  },
  {
    "id": 5,
    "category": "스타일",
    "title": "블랙워크",
    "keyword": "블랙워크"
  },
  {
    "id": 6,
    "category": "스타일",
    "title": "도트워크",
    "keyword": "도트워크"
  },
  {
    "id": 7,
    "category": "스타일",
    "title": "워터컬러",
    "keyword": "워터컬러"
  },
  {
    "id": 8,
    "category": "스타일",
    "title": "리얼리즘",
    "keyword": "리얼리즘"
  },
  {
    "id": 9,
    "category": "스타일",
    "title": "올드스쿨",
    "keyword": "올드스쿨"
  },
  {
    "id": 10,
    "category": "스타일",
    "title": "뉴스쿨",
    "keyword": "뉴스쿨"
  },
  {
    "id": 11,
    "category": "스타일",
    "title": "네오트래디셔널",
    "keyword": "네오트래디셔널"
  },
  {
    "id": 12,
    "category": "스타일",
    "title": "치카노",
    "keyword": "치카노"
  },
  {
    "id": 13,
    "category": "스타일",
    "title": "일러스트",
    "keyword": "일러스트"
  },
  {
    "id": 14,
    "category": "스타일",
    "title": "라인워크",
    "keyword": "라인워크"
  },
  {
    "id": 15,
    "category": "스타일",
    "title": "지오메트릭",
    "keyword": "지오메트릭"
  },
  {
    "id": 16,
    "category": "스타일",
    "title": "만다라",
    "keyword": "만다라"
  },
  {
    "id": 17,
    "category": "스타일",
    "title": "오너멘탈",
    "keyword": "오너멘탈"
  },
  {
    "id": 18,
    "category": "스타일",
    "title": "사이버시길",
    "keyword": "사이버시길"
  },
  {
    "id": 19,
    "category": "스타일",
    "title": "트래쉬폴카",
    "keyword": "트래쉬폴카"
  },
  {
    "id": 20,
    "category": "스타일",
    "title": "바이오메카닉",
    "keyword": "바이오메카닉"
  },
  {
    "id": 21,
    "category": "스타일",
    "title": "헤나",
    "keyword": "헤나"
  },
  {
    "id": 22,
    "category": "스타일",
    "title": "오리엔탈",
    "keyword": "오리엔탈"
  },
  {
    "id": 23,
    "category": "스타일",
    "title": "재패니즈",
    "keyword": "재패니즈"
  },
  {
    "id": 24,
    "category": "스타일",
    "title": "차이니즈",
    "keyword": "차이니즈"
  },
  {
    "id": 25,
    "category": "스타일",
    "title": "켈틱",
    "keyword": "켈틱"
  },
  {
    "id": 26,
    "category": "스타일",
    "title": "픽셀아트",
    "keyword": "픽셀아트"
  },
  {
    "id": 27,
    "category": "스타일",
    "title": "글리치",
    "keyword": "글리치"
  },
  {
    "id": 28,
    "category": "스타일",
    "title": "사이버펑크",
    "keyword": "사이버펑크"
  },
  {
    "id": 29,
    "category": "스타일",
    "title": "아메리칸트래디셔널",
    "keyword": "아메리칸트래디셔널"
  },
  {
    "id": 30,
    "category": "스타일",
    "title": "스케치",
    "keyword": "스케치"
  },
  {
    "id": 31,
    "category": "스타일",
    "title": "수묵화",
    "keyword": "수묵화"
  },
  {
    "id": 32,
    "category": "스타일",
    "title": "민화",
    "keyword": "민화"
  },
  {
    "id": 33,
    "category": "스타일",
    "title": "팝아트",
    "keyword": "팝아트"
  },
  {
    "id": 34,
    "category": "스타일",
    "title": "그래피티",
    "keyword": "그래피티"
  },
  {
    "id": 35,
    "category": "스타일",
    "title": "타이포그래피",
    "keyword": "타이포그래피"
  },
  {
    "id": 36,
    "category": "스타일",
    "title": "심볼",
    "keyword": "심볼"
  },
  {
    "id": 37,
    "category": "스타일",
    "title": "추상",
    "keyword": "추상"
  },
  {
    "id": 38,
    "category": "스타일",
    "title": "미니멀리즘",
    "keyword": "미니멀리즘"
  },
  {
    "id": 39,
    "category": "스타일",
    "title": "초상화",
    "keyword": "초상화"
  },
  {
    "id": 40,
    "category": "스타일",
    "title": "동물초상화",
    "keyword": "동물초상화"
  },
  {
    "id": 41,
    "category": "스타일",
    "title": "꽃무늬",
    "keyword": "꽃무늬"
  },
  {
    "id": 42,
    "category": "스타일",
    "title": "보태니컬",
    "keyword": "보태니컬"
  },
  {
    "id": 43,
    "category": "스타일",
    "title": "별자리",
    "keyword": "별자리"
  },
  {
    "id": 44,
    "category": "스타일",
    "title": "만화",
    "keyword": "만화"
  },
  {
    "id": 45,
    "category": "스타일",
    "title": "아니메",
    "keyword": "아니메"
  },
  {
    "id": 46,
    "category": "스타일",
    "title": "디즈니",
    "keyword": "디즈니"
  },
  {
    "id": 47,
    "category": "스타일",
    "title": "지브리",
    "keyword": "지브리"
  },
  {
    "id": 48,
    "category": "스타일",
    "title": "고전회화",
    "keyword": "고전회화"
  },
  {
    "id": 49,
    "category": "스타일",
    "title": "프린트오버",
    "keyword": "프린트오버"
  },
  {
    "id": 50,
    "category": "스타일",
    "title": "콜라주",
    "keyword": "콜라주"
  },
  {
    "id": 51,
    "category": "스타일",
    "title": "스플래터",
    "keyword": "스플래터"
  },
  {
    "id": 52,
    "category": "스타일",
    "title": "잉크블랏",
    "keyword": "잉크블랏"
  },
  {
    "id": 53,
    "category": "스타일",
    "title": "샘플러",
    "keyword": "샘플러"
  },
  {
    "id": 54,
    "category": "스타일",
    "title": "타로",
    "keyword": "타로"
  },
  {
    "id": 55,
    "category": "스타일",
    "title": "오컬트",
    "keyword": "오컬트"
  },
  {
    "id": 56,
    "category": "스타일",
    "title": "고딕",
    "keyword": "고딕"
  },
  {
    "id": 57,
    "category": "스타일",
    "title": "다크아트",
    "keyword": "다크아트"
  },
  {
    "id": 58,
    "category": "스타일",
    "title": "스팀펑크",
    "keyword": "스팀펑크"
  },
  {
    "id": 59,
    "category": "스타일",
    "title": "복고",
    "keyword": "복고"
  },
  {
    "id": 60,
    "category": "스타일",
    "title": "Y2K",
    "keyword": "Y2K"
  },
  {
    "id": 61,
    "category": "부위",
    "title": "손목 타투",
    "keyword": "손목 타투"
  },
  {
    "id": 62,
    "category": "부위",
    "title": "발목 타투",
    "keyword": "발목 타투"
  },
  {
    "id": 63,
    "category": "부위",
    "title": "어깨 타투",
    "keyword": "어깨 타투"
  },
  {
    "id": 64,
    "category": "부위",
    "title": "팔뚝 타투",
    "keyword": "팔뚝 타투"
  },
  {
    "id": 65,
    "category": "부위",
    "title": "이두 타투",
    "keyword": "이두 타투"
  },
  {
    "id": 66,
    "category": "부위",
    "title": "삼두 타투",
    "keyword": "삼두 타투"
  },
  {
    "id": 67,
    "category": "부위",
    "title": "전완 타투",
    "keyword": "전완 타투"
  },
  {
    "id": 68,
    "category": "부위",
    "title": "손등 타투",
    "keyword": "손등 타투"
  },
  {
    "id": 69,
    "category": "부위",
    "title": "손가락 타투",
    "keyword": "손가락 타투"
  },
  {
    "id": 70,
    "category": "부위",
    "title": "발등 타투",
    "keyword": "발등 타투"
  },
  {
    "id": 71,
    "category": "부위",
    "title": "발가락 타투",
    "keyword": "발가락 타투"
  },
  {
    "id": 72,
    "category": "부위",
    "title": "쇄골 타투",
    "keyword": "쇄골 타투"
  },
  {
    "id": 73,
    "category": "부위",
    "title": "목 타투",
    "keyword": "목 타투"
  },
  {
    "id": 74,
    "category": "부위",
    "title": "귀뒤 타투",
    "keyword": "귀뒤 타투"
  },
  {
    "id": 75,
    "category": "부위",
    "title": "관자놀이 타투",
    "keyword": "관자놀이 타투"
  },
  {
    "id": 76,
    "category": "부위",
    "title": "얼굴 타투",
    "keyword": "얼굴 타투"
  },
  {
    "id": 77,
    "category": "부위",
    "title": "이마 타투",
    "keyword": "이마 타투"
  },
  {
    "id": 78,
    "category": "부위",
    "title": "턱 타투",
    "keyword": "턱 타투"
  },
  {
    "id": 79,
    "category": "부위",
    "title": "가슴 타투",
    "keyword": "가슴 타투"
  },
  {
    "id": 80,
    "category": "부위",
    "title": "유두주위 타투",
    "keyword": "유두주위 타투"
  },
  {
    "id": 81,
    "category": "부위",
    "title": "갈비뼈 타투",
    "keyword": "갈비뼈 타투"
  },
  {
    "id": 82,
    "category": "부위",
    "title": "옆구리 타투",
    "keyword": "옆구리 타투"
  },
  {
    "id": 83,
    "category": "부위",
    "title": "복부 타투",
    "keyword": "복부 타투"
  },
  {
    "id": 84,
    "category": "부위",
    "title": "배꼽 타투",
    "keyword": "배꼽 타투"
  },
  {
    "id": 85,
    "category": "부위",
    "title": "허리 타투",
    "keyword": "허리 타투"
  },
  {
    "id": 86,
    "category": "부위",
    "title": "골반 타투",
    "keyword": "골반 타투"
  },
  {
    "id": 87,
    "category": "부위",
    "title": "엉덩이 타투",
    "keyword": "엉덩이 타투"
  },
  {
    "id": 88,
    "category": "부위",
    "title": "허벅지 타투",
    "keyword": "허벅지 타투"
  },
  {
    "id": 89,
    "category": "부위",
    "title": "무릎 타투",
    "keyword": "무릎 타투"
  },
  {
    "id": 90,
    "category": "부위",
    "title": "종아리 타투",
    "keyword": "종아리 타투"
  },
  {
    "id": 91,
    "category": "부위",
    "title": "정강이 타투",
    "keyword": "정강이 타투"
  },
  {
    "id": 92,
    "category": "부위",
    "title": "발뒤꿈치 타투",
    "keyword": "발뒤꿈치 타투"
  },
  {
    "id": 93,
    "category": "부위",
    "title": "등 전체 타투",
    "keyword": "등 전체 타투"
  },
  {
    "id": 94,
    "category": "부위",
    "title": "어깨뼈 타투",
    "keyword": "어깨뼈 타투"
  },
  {
    "id": 95,
    "category": "부위",
    "title": "척추 타투",
    "keyword": "척추 타투"
  },
  {
    "id": 96,
    "category": "부위",
    "title": "라이너 타투",
    "keyword": "라이너 타투"
  },
  {
    "id": 97,
    "category": "부위",
    "title": "팔 슬리브",
    "keyword": "팔 슬리브"
  },
  {
    "id": 98,
    "category": "부위",
    "title": "다리 슬리브",
    "keyword": "다리 슬리브"
  },
  {
    "id": 99,
    "category": "부위",
    "title": "백 피스",
    "keyword": "백 피스"
  },
  {
    "id": 100,
    "category": "부위",
    "title": "체스트 피스",
    "keyword": "체스트 피스"
  },
  {
    "id": 101,
    "category": "부위",
    "title": "넥피스",
    "keyword": "넥피스"
  },
  {
    "id": 102,
    "category": "부위",
    "title": "이너 바이셉",
    "keyword": "이너 바이셉"
  },
  {
    "id": 103,
    "category": "부위",
    "title": "암핏 타투",
    "keyword": "암핏 타투"
  },
  {
    "id": 104,
    "category": "부위",
    "title": "내전근 타투",
    "keyword": "내전근 타투"
  },
  {
    "id": 105,
    "category": "부위",
    "title": "엘보 타투",
    "keyword": "엘보 타투"
  },
  {
    "id": 106,
    "category": "부위",
    "title": "콜라본 타투",
    "keyword": "콜라본 타투"
  },
  {
    "id": 107,
    "category": "부위",
    "title": "아래팔 타투",
    "keyword": "아래팔 타투"
  },
  {
    "id": 108,
    "category": "부위",
    "title": "허리둘레 타투",
    "keyword": "허리둘레 타투"
  },
  {
    "id": 109,
    "category": "부위",
    "title": "스플릿 타투",
    "keyword": "스플릿 타투"
  },
  {
    "id": 110,
    "category": "부위",
    "title": "양 손목 매칭",
    "keyword": "양 손목 매칭"
  },
  {
    "id": 111,
    "category": "모티브",
    "title": "장미 타투",
    "keyword": "장미 타투"
  },
  {
    "id": 112,
    "category": "모티브",
    "title": "벚꽃 타투",
    "keyword": "벚꽃 타투"
  },
  {
    "id": 113,
    "category": "모티브",
    "title": "연꽃 타투",
    "keyword": "연꽃 타투"
  },
  {
    "id": 114,
    "category": "모티브",
    "title": "튤립 타투",
    "keyword": "튤립 타투"
  },
  {
    "id": 115,
    "category": "모티브",
    "title": "해바라기 타투",
    "keyword": "해바라기 타투"
  },
  {
    "id": 116,
    "category": "모티브",
    "title": "백합 타투",
    "keyword": "백합 타투"
  },
  {
    "id": 117,
    "category": "모티브",
    "title": "수국 타투",
    "keyword": "수국 타투"
  },
  {
    "id": 118,
    "category": "모티브",
    "title": "동백 타투",
    "keyword": "동백 타투"
  },
  {
    "id": 119,
    "category": "모티브",
    "title": "데이지 타투",
    "keyword": "데이지 타투"
  },
  {
    "id": 120,
    "category": "모티브",
    "title": "양귀비 타투",
    "keyword": "양귀비 타투"
  },
  {
    "id": 121,
    "category": "모티브",
    "title": "호랑이 타투",
    "keyword": "호랑이 타투"
  },
  {
    "id": 122,
    "category": "모티브",
    "title": "용 타투",
    "keyword": "용 타투"
  },
  {
    "id": 123,
    "category": "모티브",
    "title": "봉황 타투",
    "keyword": "봉황 타투"
  },
  {
    "id": 124,
    "category": "모티브",
    "title": "잉어 타투",
    "keyword": "잉어 타투"
  },
  {
    "id": 125,
    "category": "모티브",
    "title": "학 타투",
    "keyword": "학 타투"
  },
  {
    "id": 126,
    "category": "모티브",
    "title": "사자 타투",
    "keyword": "사자 타투"
  },
  {
    "id": 127,
    "category": "모티브",
    "title": "곰 타투",
    "keyword": "곰 타투"
  },
  {
    "id": 128,
    "category": "모티브",
    "title": "늑대 타투",
    "keyword": "늑대 타투"
  },
  {
    "id": 129,
    "category": "모티브",
    "title": "여우 타투",
    "keyword": "여우 타투"
  },
  {
    "id": 130,
    "category": "모티브",
    "title": "사슴 타투",
    "keyword": "사슴 타투"
  },
  {
    "id": 131,
    "category": "모티브",
    "title": "말 타투",
    "keyword": "말 타투"
  },
  {
    "id": 132,
    "category": "모티브",
    "title": "코끼리 타투",
    "keyword": "코끼리 타투"
  },
  {
    "id": 133,
    "category": "모티브",
    "title": "고양이 타투",
    "keyword": "고양이 타투"
  },
  {
    "id": 134,
    "category": "모티브",
    "title": "강아지 타투",
    "keyword": "강아지 타투"
  },
  {
    "id": 135,
    "category": "모티브",
    "title": "토끼 타투",
    "keyword": "토끼 타투"
  },
  {
    "id": 136,
    "category": "모티브",
    "title": "뱀 타투",
    "keyword": "뱀 타투"
  },
  {
    "id": 137,
    "category": "모티브",
    "title": "거미 타투",
    "keyword": "거미 타투"
  },
  {
    "id": 138,
    "category": "모티브",
    "title": "나비 타투",
    "keyword": "나비 타투"
  },
  {
    "id": 139,
    "category": "모티브",
    "title": "꿀벌 타투",
    "keyword": "꿀벌 타투"
  },
  {
    "id": 140,
    "category": "모티브",
    "title": "잠자리 타투",
    "keyword": "잠자리 타투"
  },
  {
    "id": 141,
    "category": "모티브",
    "title": "까마귀 타투",
    "keyword": "까마귀 타투"
  },
  {
    "id": 142,
    "category": "모티브",
    "title": "부엉이 타투",
    "keyword": "부엉이 타투"
  },
  {
    "id": 143,
    "category": "모티브",
    "title": "독수리 타투",
    "keyword": "독수리 타투"
  },
  {
    "id": 144,
    "category": "모티브",
    "title": "매 타투",
    "keyword": "매 타투"
  },
  {
    "id": 145,
    "category": "모티브",
    "title": "공작 타투",
    "keyword": "공작 타투"
  },
  {
    "id": 146,
    "category": "모티브",
    "title": "달 타투",
    "keyword": "달 타투"
  },
  {
    "id": 147,
    "category": "모티브",
    "title": "해 타투",
    "keyword": "해 타투"
  },
  {
    "id": 148,
    "category": "모티브",
    "title": "별자리 타투",
    "keyword": "별자리 타투"
  },
  {
    "id": 149,
    "category": "모티브",
    "title": "행성 타투",
    "keyword": "행성 타투"
  },
  {
    "id": 150,
    "category": "모티브",
    "title": "구름 타투",
    "keyword": "구름 타투"
  },
  {
    "id": 151,
    "category": "모티브",
    "title": "파도 타투",
    "keyword": "파도 타투"
  },
  {
    "id": 152,
    "category": "모티브",
    "title": "산 타투",
    "keyword": "산 타투"
  },
  {
    "id": 153,
    "category": "모티브",
    "title": "나무 타투",
    "keyword": "나무 타투"
  },
  {
    "id": 154,
    "category": "모티브",
    "title": "잎 타투",
    "keyword": "잎 타투"
  },
  {
    "id": 155,
    "category": "모티브",
    "title": "열쇠 타투",
    "keyword": "열쇠 타투"
  },
  {
    "id": 156,
    "category": "모티브",
    "title": "자물쇠 타투",
    "keyword": "자물쇠 타투"
  },
  {
    "id": 157,
    "category": "모티브",
    "title": "나침반 타투",
    "keyword": "나침반 타투"
  },
  {
    "id": 158,
    "category": "모티브",
    "title": "지도 타투",
    "keyword": "지도 타투"
  },
  {
    "id": 159,
    "category": "모티브",
    "title": "시계 타투",
    "keyword": "시계 타투"
  },
  {
    "id": 160,
    "category": "모티브",
    "title": "왕관 타투",
    "keyword": "왕관 타투"
  },
  {
    "id": 161,
    "category": "모티브",
    "title": "검 타투",
    "keyword": "검 타투"
  },
  {
    "id": 162,
    "category": "모티브",
    "title": "화살 타투",
    "keyword": "화살 타투"
  },
  {
    "id": 163,
    "category": "모티브",
    "title": "깃털 타투",
    "keyword": "깃털 타투"
  },
  {
    "id": 164,
    "category": "모티브",
    "title": "리본 타투",
    "keyword": "리본 타투"
  },
  {
    "id": 165,
    "category": "모티브",
    "title": "심장 타투",
    "keyword": "심장 타투"
  },
  {
    "id": 166,
    "category": "모티브",
    "title": "두개골 타투",
    "keyword": "두개골 타투"
  },
  {
    "id": 167,
    "category": "모티브",
    "title": "해골꽃 타투",
    "keyword": "해골꽃 타투"
  },
  {
    "id": 168,
    "category": "모티브",
    "title": "뼈 타투",
    "keyword": "뼈 타투"
  },
  {
    "id": 169,
    "category": "모티브",
    "title": "눈물 타투",
    "keyword": "눈물 타투"
  },
  {
    "id": 170,
    "category": "모티브",
    "title": "이름 타투",
    "keyword": "이름 타투"
  },
  {
    "id": 171,
    "category": "관리",
    "title": "타투 직후 첫 24시간",
    "keyword": "타투 직후 첫 24시간"
  },
  {
    "id": 172,
    "category": "관리",
    "title": "타투 첫 일주일 케어",
    "keyword": "타투 첫 일주일 케어"
  },
  {
    "id": 173,
    "category": "관리",
    "title": "타투 보습제 추천",
    "keyword": "타투 보습제 추천"
  },
  {
    "id": 174,
    "category": "관리",
    "title": "타투 비누 선택법",
    "keyword": "타투 비누 선택법"
  },
  {
    "id": 175,
    "category": "관리",
    "title": "타투 후 햇빛 노출",
    "keyword": "타투 후 햇빛 노출"
  },
  {
    "id": 176,
    "category": "관리",
    "title": "타투 후 수영",
    "keyword": "타투 후 수영"
  },
  {
    "id": 177,
    "category": "관리",
    "title": "타투 후 사우나",
    "keyword": "타투 후 사우나"
  },
  {
    "id": 178,
    "category": "관리",
    "title": "타투 후 운동",
    "keyword": "타투 후 운동"
  },
  {
    "id": 179,
    "category": "관리",
    "title": "타투 후 옷차림",
    "keyword": "타투 후 옷차림"
  },
  {
    "id": 180,
    "category": "관리",
    "title": "타투 딱지 관리",
    "keyword": "타투 딱지 관리"
  },
  {
    "id": 181,
    "category": "관리",
    "title": "타투 가려움 대처",
    "keyword": "타투 가려움 대처"
  },
  {
    "id": 182,
    "category": "관리",
    "title": "타투 부분 색바램",
    "keyword": "타투 부분 색바램"
  },
  {
    "id": 183,
    "category": "관리",
    "title": "타투 수정 시기",
    "keyword": "타투 수정 시기"
  },
  {
    "id": 184,
    "category": "관리",
    "title": "타투 통증 관리",
    "keyword": "타투 통증 관리"
  },
  {
    "id": 185,
    "category": "관리",
    "title": "타투 부어오름",
    "keyword": "타투 부어오름"
  },
  {
    "id": 186,
    "category": "관리",
    "title": "타투 진물",
    "keyword": "타투 진물"
  },
  {
    "id": 187,
    "category": "관리",
    "title": "타투 연고",
    "keyword": "타투 연고"
  },
  {
    "id": 188,
    "category": "관리",
    "title": "랩핑 vs 세컨드스킨",
    "keyword": "랩핑 vs 세컨드스킨"
  },
  {
    "id": 189,
    "category": "관리",
    "title": "타투 샤워 가이드",
    "keyword": "타투 샤워 가이드"
  },
  {
    "id": 190,
    "category": "관리",
    "title": "타투 후 음주",
    "keyword": "타투 후 음주"
  },
  {
    "id": 191,
    "category": "관리",
    "title": "타투 후 흡연",
    "keyword": "타투 후 흡연"
  },
  {
    "id": 192,
    "category": "관리",
    "title": "타투 노화 대비",
    "keyword": "타투 노화 대비"
  },
  {
    "id": 193,
    "category": "관리",
    "title": "타투 자외선 차단제",
    "keyword": "타투 자외선 차단제"
  },
  {
    "id": 194,
    "category": "관리",
    "title": "타투 색 유지법",
    "keyword": "타투 색 유지법"
  },
  {
    "id": 195,
    "category": "관리",
    "title": "타투 보정",
    "keyword": "타투 보정"
  },
  {
    "id": 196,
    "category": "관리",
    "title": "타투 알러지 증상",
    "keyword": "타투 알러지 증상"
  },
  {
    "id": 197,
    "category": "관리",
    "title": "타투 감염 신호",
    "keyword": "타투 감염 신호"
  },
  {
    "id": 198,
    "category": "관리",
    "title": "오래된 타투 케어",
    "keyword": "오래된 타투 케어"
  },
  {
    "id": 199,
    "category": "관리",
    "title": "여름철 타투 관리",
    "keyword": "여름철 타투 관리"
  },
  {
    "id": 200,
    "category": "관리",
    "title": "겨울철 타투 관리",
    "keyword": "겨울철 타투 관리"
  },
  {
    "id": 201,
    "category": "역사",
    "title": "한국 타투의 역사",
    "keyword": "한국 타투의 역사"
  },
  {
    "id": 202,
    "category": "역사",
    "title": "일본 이레즈미의 역사",
    "keyword": "일본 이레즈미의 역사"
  },
  {
    "id": 203,
    "category": "역사",
    "title": "마오리 모코의 의미",
    "keyword": "마오리 모코의 의미"
  },
  {
    "id": 204,
    "category": "역사",
    "title": "폴리네시안 타투 문화",
    "keyword": "폴리네시안 타투 문화"
  },
  {
    "id": 205,
    "category": "역사",
    "title": "사모안 타투의 전통",
    "keyword": "사모안 타투의 전통"
  },
  {
    "id": 206,
    "category": "역사",
    "title": "켈틱 타투의 기원",
    "keyword": "켈틱 타투의 기원"
  },
  {
    "id": 207,
    "category": "역사",
    "title": "아메리칸 트래디셔널의 탄생",
    "keyword": "아메리칸 트래디셔널의 탄생"
  },
  {
    "id": 208,
    "category": "역사",
    "title": "러시아 죄수 타투의 코드",
    "keyword": "러시아 죄수 타투의 코드"
  },
  {
    "id": 209,
    "category": "역사",
    "title": "야쿠자 타투 문화",
    "keyword": "야쿠자 타투 문화"
  },
  {
    "id": 210,
    "category": "역사",
    "title": "북유럽 바이킹 룬 타투",
    "keyword": "북유럽 바이킹 룬 타투"
  },
  {
    "id": 211,
    "category": "역사",
    "title": "이집트 타투의 역사",
    "keyword": "이집트 타투의 역사"
  },
  {
    "id": 212,
    "category": "역사",
    "title": "서양 타투의 발전",
    "keyword": "서양 타투의 발전"
  },
  {
    "id": 213,
    "category": "역사",
    "title": "선원 타투의 의미",
    "keyword": "선원 타투의 의미"
  },
  {
    "id": 214,
    "category": "역사",
    "title": "수병 타투 심볼",
    "keyword": "수병 타투 심볼"
  },
  {
    "id": 215,
    "category": "역사",
    "title": "헤나의 인도 전통",
    "keyword": "헤나의 인도 전통"
  },
  {
    "id": 216,
    "category": "역사",
    "title": "치카노 타투의 멕시코 뿌리",
    "keyword": "치카노 타투의 멕시코 뿌리"
  },
  {
    "id": 217,
    "category": "역사",
    "title": "조선시대 묵형의 흔적",
    "keyword": "조선시대 묵형의 흔적"
  },
  {
    "id": 218,
    "category": "역사",
    "title": "삼국시대 문신 기록",
    "keyword": "삼국시대 문신 기록"
  },
  {
    "id": 219,
    "category": "역사",
    "title": "타투의 현대적 부활",
    "keyword": "타투의 현대적 부활"
  },
  {
    "id": 220,
    "category": "역사",
    "title": "K-타투의 글로벌 확산",
    "keyword": "K-타투의 글로벌 확산"
  },
  {
    "id": 221,
    "category": "역사",
    "title": "할리우드 셀럽 타투",
    "keyword": "할리우드 셀럽 타투"
  },
  {
    "id": 222,
    "category": "역사",
    "title": "BTS와 K-타투 트렌드",
    "keyword": "BTS와 K-타투 트렌드"
  },
  {
    "id": 223,
    "category": "역사",
    "title": "프리즌 타투의 상징",
    "keyword": "프리즌 타투의 상징"
  },
  {
    "id": 224,
    "category": "역사",
    "title": "고대 그리스 로마 타투",
    "keyword": "고대 그리스 로마 타투"
  },
  {
    "id": 225,
    "category": "역사",
    "title": "아프리카 부족 타투",
    "keyword": "아프리카 부족 타투"
  },
  {
    "id": 226,
    "category": "역사",
    "title": "잉카 타투 문화",
    "keyword": "잉카 타투 문화"
  },
  {
    "id": 227,
    "category": "역사",
    "title": "서커스 타투의 전성기",
    "keyword": "서커스 타투의 전성기"
  },
  {
    "id": 228,
    "category": "역사",
    "title": "1차 세계대전과 군인 타투",
    "keyword": "1차 세계대전과 군인 타투"
  },
  {
    "id": 229,
    "category": "역사",
    "title": "사이버펑크와 타투 미학",
    "keyword": "사이버펑크와 타투 미학"
  },
  {
    "id": 230,
    "category": "역사",
    "title": "타투 박람회의 역사",
    "keyword": "타투 박람회의 역사"
  },
  {
    "id": 231,
    "category": "장비",
    "title": "코일 머신과 로터리 머신 차이",
    "keyword": "코일 머신과 로터리 머신 차이"
  },
  {
    "id": 232,
    "category": "장비",
    "title": "타투 머신 종류와 특징",
    "keyword": "타투 머신 종류와 특징"
  },
  {
    "id": 233,
    "category": "장비",
    "title": "타투 잉크 안전성 가이드",
    "keyword": "타투 잉크 안전성 가이드"
  },
  {
    "id": 234,
    "category": "장비",
    "title": "비건 타투 잉크",
    "keyword": "비건 타투 잉크"
  },
  {
    "id": 235,
    "category": "장비",
    "title": "유럽 REACH 잉크 규제",
    "keyword": "유럽 REACH 잉크 규제"
  },
  {
    "id": 236,
    "category": "장비",
    "title": "타투 니들 종류",
    "keyword": "타투 니들 종류"
  },
  {
    "id": 237,
    "category": "장비",
    "title": "라이너 vs 셰이더 니들",
    "keyword": "라이너 vs 셰이더 니들"
  },
  {
    "id": 238,
    "category": "장비",
    "title": "1회용 카트리지 니들",
    "keyword": "1회용 카트리지 니들"
  },
  {
    "id": 239,
    "category": "장비",
    "title": "타투 그립 선택",
    "keyword": "타투 그립 선택"
  },
  {
    "id": 240,
    "category": "장비",
    "title": "타투 전원공급장치",
    "keyword": "타투 전원공급장치"
  },
  {
    "id": 241,
    "category": "장비",
    "title": "풋페달 사용법",
    "keyword": "풋페달 사용법"
  },
  {
    "id": 242,
    "category": "장비",
    "title": "타투 의자와 베드",
    "keyword": "타투 의자와 베드"
  },
  {
    "id": 243,
    "category": "장비",
    "title": "위생 라이트",
    "keyword": "위생 라이트"
  },
  {
    "id": 244,
    "category": "장비",
    "title": "스텐실 종류",
    "keyword": "스텐실 종류"
  },
  {
    "id": 245,
    "category": "장비",
    "title": "프리핸드 vs 스텐실",
    "keyword": "프리핸드 vs 스텐실"
  },
  {
    "id": 246,
    "category": "장비",
    "title": "잉크 컵",
    "keyword": "잉크 컵"
  },
  {
    "id": 247,
    "category": "장비",
    "title": "베이스라인 잉크",
    "keyword": "베이스라인 잉크"
  },
  {
    "id": 248,
    "category": "장비",
    "title": "그레이워시",
    "keyword": "그레이워시"
  },
  {
    "id": 249,
    "category": "장비",
    "title": "수성 잉크",
    "keyword": "수성 잉크"
  },
  {
    "id": 250,
    "category": "장비",
    "title": "오가닉 잉크",
    "keyword": "오가닉 잉크"
  },
  {
    "id": 251,
    "category": "장비",
    "title": "타투 머신 세팅",
    "keyword": "타투 머신 세팅"
  },
  {
    "id": 252,
    "category": "장비",
    "title": "니들 깊이 조절",
    "keyword": "니들 깊이 조절"
  },
  {
    "id": 253,
    "category": "장비",
    "title": "초보 머신 추천",
    "keyword": "초보 머신 추천"
  },
  {
    "id": 254,
    "category": "장비",
    "title": "타투 워크스테이션 셋업",
    "keyword": "타투 워크스테이션 셋업"
  },
  {
    "id": 255,
    "category": "장비",
    "title": "감염 예방 도구",
    "keyword": "감염 예방 도구"
  },
  {
    "id": 256,
    "category": "법률",
    "title": "한국 타투 합법화 현황",
    "keyword": "한국 타투 합법화 현황"
  },
  {
    "id": 257,
    "category": "법률",
    "title": "타투 자격증 제도",
    "keyword": "타투 자격증 제도"
  },
  {
    "id": 258,
    "category": "법률",
    "title": "타투와 MRI",
    "keyword": "타투와 MRI"
  },
  {
    "id": 259,
    "category": "법률",
    "title": "타투 후 헌혈",
    "keyword": "타투 후 헌혈"
  },
  {
    "id": 260,
    "category": "법률",
    "title": "타투 알러지 종류",
    "keyword": "타투 알러지 종류"
  },
  {
    "id": 261,
    "category": "법률",
    "title": "타투와 흉터",
    "keyword": "타투와 흉터"
  },
  {
    "id": 262,
    "category": "법률",
    "title": "타투와 켈로이드",
    "keyword": "타투와 켈로이드"
  },
  {
    "id": 263,
    "category": "법률",
    "title": "임신 중 타투",
    "keyword": "임신 중 타투"
  },
  {
    "id": 264,
    "category": "법률",
    "title": "수유 중 타투",
    "keyword": "수유 중 타투"
  },
  {
    "id": 265,
    "category": "법률",
    "title": "당뇨 환자 타투",
    "keyword": "당뇨 환자 타투"
  },
  {
    "id": 266,
    "category": "법률",
    "title": "타투와 군 입대",
    "keyword": "타투와 군 입대"
  },
  {
    "id": 267,
    "category": "법률",
    "title": "타투와 직장 면접",
    "keyword": "타투와 직장 면접"
  },
  {
    "id": 268,
    "category": "법률",
    "title": "타투와 해외여행",
    "keyword": "타투와 해외여행"
  },
  {
    "id": 269,
    "category": "법률",
    "title": "타투와 일본 온천",
    "keyword": "타투와 일본 온천"
  },
  {
    "id": 270,
    "category": "법률",
    "title": "타투와 학교",
    "keyword": "타투와 학교"
  },
  {
    "id": 271,
    "category": "법률",
    "title": "타투와 보험",
    "keyword": "타투와 보험"
  },
  {
    "id": 272,
    "category": "법률",
    "title": "타투 후 약 복용",
    "keyword": "타투 후 약 복용"
  },
  {
    "id": 273,
    "category": "법률",
    "title": "타투와 피부질환",
    "keyword": "타투와 피부질환"
  },
  {
    "id": 274,
    "category": "법률",
    "title": "타투와 헌혈 가능 시기",
    "keyword": "타투와 헌혈 가능 시기"
  },
  {
    "id": 275,
    "category": "법률",
    "title": "미성년자 타투 금지",
    "keyword": "미성년자 타투 금지"
  },
  {
    "id": 276,
    "category": "뷰티",
    "title": "반영구 눈썹 종류",
    "keyword": "반영구 눈썹 종류"
  },
  {
    "id": 277,
    "category": "뷰티",
    "title": "엠보 vs 콤보 눈썹",
    "keyword": "엠보 vs 콤보 눈썹"
  },
  {
    "id": 278,
    "category": "뷰티",
    "title": "콤브로우",
    "keyword": "콤브로우"
  },
  {
    "id": 279,
    "category": "뷰티",
    "title": "옴브레 파우더 브로우",
    "keyword": "옴브레 파우더 브로우"
  },
  {
    "id": 280,
    "category": "뷰티",
    "title": "마이크로블레이딩",
    "keyword": "마이크로블레이딩"
  },
  {
    "id": 281,
    "category": "뷰티",
    "title": "내추럴 눈썹",
    "keyword": "내추럴 눈썹"
  },
  {
    "id": 282,
    "category": "뷰티",
    "title": "남자 반영구 눈썹",
    "keyword": "남자 반영구 눈썹"
  },
  {
    "id": 283,
    "category": "뷰티",
    "title": "헤어라인 반영구",
    "keyword": "헤어라인 반영구"
  },
  {
    "id": 284,
    "category": "뷰티",
    "title": "남자 헤어라인 시술",
    "keyword": "남자 헤어라인 시술"
  },
  {
    "id": 285,
    "category": "뷰티",
    "title": "두피 문신 SMP",
    "keyword": "두피 문신 SMP"
  },
  {
    "id": 286,
    "category": "뷰티",
    "title": "탈모 두피 타투",
    "keyword": "탈모 두피 타투"
  },
  {
    "id": 287,
    "category": "뷰티",
    "title": "반영구 입술",
    "keyword": "반영구 입술"
  },
  {
    "id": 288,
    "category": "뷰티",
    "title": "립 블러시",
    "keyword": "립 블러시"
  },
  {
    "id": 289,
    "category": "뷰티",
    "title": "립 라인",
    "keyword": "립 라인"
  },
  {
    "id": 290,
    "category": "뷰티",
    "title": "립 옴브레",
    "keyword": "립 옴브레"
  },
  {
    "id": 291,
    "category": "뷰티",
    "title": "아이라인 반영구",
    "keyword": "아이라인 반영구"
  },
  {
    "id": 292,
    "category": "뷰티",
    "title": "속눈썹 라인",
    "keyword": "속눈썹 라인"
  },
  {
    "id": 293,
    "category": "뷰티",
    "title": "속눈썹 반영구",
    "keyword": "속눈썹 반영구"
  },
  {
    "id": 294,
    "category": "뷰티",
    "title": "윤곽 반영구",
    "keyword": "윤곽 반영구"
  },
  {
    "id": 295,
    "category": "뷰티",
    "title": "치크 블러시 반영구",
    "keyword": "치크 블러시 반영구"
  },
  {
    "id": 296,
    "category": "뷰티",
    "title": "남자 콧수염 반영구",
    "keyword": "남자 콧수염 반영구"
  },
  {
    "id": 297,
    "category": "뷰티",
    "title": "반영구 색소 종류",
    "keyword": "반영구 색소 종류"
  },
  {
    "id": 298,
    "category": "뷰티",
    "title": "반영구 안전성",
    "keyword": "반영구 안전성"
  },
  {
    "id": 299,
    "category": "뷰티",
    "title": "반영구 지속 기간",
    "keyword": "반영구 지속 기간"
  },
  {
    "id": 300,
    "category": "뷰티",
    "title": "반영구 리터치 시기",
    "keyword": "반영구 리터치 시기"
  },
  {
    "id": 301,
    "category": "뷰티",
    "title": "반영구 부작용",
    "keyword": "반영구 부작용"
  },
  {
    "id": 302,
    "category": "뷰티",
    "title": "반영구 제거",
    "keyword": "반영구 제거"
  },
  {
    "id": 303,
    "category": "뷰티",
    "title": "반영구와 타투의 차이",
    "keyword": "반영구와 타투의 차이"
  },
  {
    "id": 304,
    "category": "뷰티",
    "title": "반영구 디자인 트렌드",
    "keyword": "반영구 디자인 트렌드"
  },
  {
    "id": 305,
    "category": "뷰티",
    "title": "반영구 가격대",
    "keyword": "반영구 가격대"
  },
  {
    "id": 306,
    "category": "리무벌",
    "title": "타투 레이저 제거 원리",
    "keyword": "타투 레이저 제거 원리"
  },
  {
    "id": 307,
    "category": "리무벌",
    "title": "피코초 vs Q-스위치",
    "keyword": "피코초 vs Q-스위치"
  },
  {
    "id": 308,
    "category": "리무벌",
    "title": "타투 제거 비용",
    "keyword": "타투 제거 비용"
  },
  {
    "id": 309,
    "category": "리무벌",
    "title": "색깔별 타투 제거 난이도",
    "keyword": "색깔별 타투 제거 난이도"
  },
  {
    "id": 310,
    "category": "리무벌",
    "title": "검은색 타투 제거",
    "keyword": "검은색 타투 제거"
  },
  {
    "id": 311,
    "category": "리무벌",
    "title": "컬러 타투 제거",
    "keyword": "컬러 타투 제거"
  },
  {
    "id": 312,
    "category": "리무벌",
    "title": "부분 제거",
    "keyword": "부분 제거"
  },
  {
    "id": 313,
    "category": "리무벌",
    "title": "페이딩 후 커버업",
    "keyword": "페이딩 후 커버업"
  },
  {
    "id": 314,
    "category": "리무벌",
    "title": "커버업 디자인 팁",
    "keyword": "커버업 디자인 팁"
  },
  {
    "id": 315,
    "category": "리무벌",
    "title": "블랙아웃 커버업",
    "keyword": "블랙아웃 커버업"
  },
  {
    "id": 316,
    "category": "리무벌",
    "title": "화이트 잉크 커버업",
    "keyword": "화이트 잉크 커버업"
  },
  {
    "id": 317,
    "category": "리무벌",
    "title": "타투 흉터 예방",
    "keyword": "타투 흉터 예방"
  },
  {
    "id": 318,
    "category": "리무벌",
    "title": "레이저 후 케어",
    "keyword": "레이저 후 케어"
  },
  {
    "id": 319,
    "category": "리무벌",
    "title": "타투 제거 통증",
    "keyword": "타투 제거 통증"
  },
  {
    "id": 320,
    "category": "리무벌",
    "title": "레이저 횟수",
    "keyword": "레이저 횟수"
  },
  {
    "id": 321,
    "category": "리무벌",
    "title": "레이저 부작용",
    "keyword": "레이저 부작용"
  },
  {
    "id": 322,
    "category": "리무벌",
    "title": "레이저 후 색소침착",
    "keyword": "레이저 후 색소침착"
  },
  {
    "id": 323,
    "category": "리무벌",
    "title": "오래된 타투 제거",
    "keyword": "오래된 타투 제거"
  },
  {
    "id": 324,
    "category": "리무벌",
    "title": "셀프 제거의 위험",
    "keyword": "셀프 제거의 위험"
  },
  {
    "id": 325,
    "category": "리무벌",
    "title": "타투 제거 vs 커버업 선택",
    "keyword": "타투 제거 vs 커버업 선택"
  },
  {
    "id": 326,
    "category": "트렌드",
    "title": "2026 타투 트렌드",
    "keyword": "2026 타투 트렌드"
  },
  {
    "id": 327,
    "category": "트렌드",
    "title": "20대 인기 타투",
    "keyword": "20대 인기 타투"
  },
  {
    "id": 328,
    "category": "트렌드",
    "title": "30대 인기 타투",
    "keyword": "30대 인기 타투"
  },
  {
    "id": 329,
    "category": "트렌드",
    "title": "40대 타투 디자인",
    "keyword": "40대 타투 디자인"
  },
  {
    "id": 330,
    "category": "트렌드",
    "title": "10대가 알아야 할 타투 진실",
    "keyword": "10대가 알아야 할 타투 진실"
  },
  {
    "id": 331,
    "category": "트렌드",
    "title": "남자 첫 타투 추천",
    "keyword": "남자 첫 타투 추천"
  },
  {
    "id": 332,
    "category": "트렌드",
    "title": "여자 첫 타투 추천",
    "keyword": "여자 첫 타투 추천"
  },
  {
    "id": 333,
    "category": "트렌드",
    "title": "커플 타투 아이디어",
    "keyword": "커플 타투 아이디어"
  },
  {
    "id": 334,
    "category": "트렌드",
    "title": "부부 타투",
    "keyword": "부부 타투"
  },
  {
    "id": 335,
    "category": "트렌드",
    "title": "친구 매칭 타투",
    "keyword": "친구 매칭 타투"
  },
  {
    "id": 336,
    "category": "트렌드",
    "title": "부모 자식 타투",
    "keyword": "부모 자식 타투"
  },
  {
    "id": 337,
    "category": "트렌드",
    "title": "추모 타투",
    "keyword": "추모 타투"
  },
  {
    "id": 338,
    "category": "트렌드",
    "title": "반려동물 추모",
    "keyword": "반려동물 추모"
  },
  {
    "id": 339,
    "category": "트렌드",
    "title": "결혼 기념 타투",
    "keyword": "결혼 기념 타투"
  },
  {
    "id": 340,
    "category": "트렌드",
    "title": "출산 기념 타투",
    "keyword": "출산 기념 타투"
  },
  {
    "id": 341,
    "category": "트렌드",
    "title": "졸업 기념 타투",
    "keyword": "졸업 기념 타투"
  },
  {
    "id": 342,
    "category": "트렌드",
    "title": "이름 새기기 의미",
    "keyword": "이름 새기기 의미"
  },
  {
    "id": 343,
    "category": "트렌드",
    "title": "이니셜 타투",
    "keyword": "이니셜 타투"
  },
  {
    "id": 344,
    "category": "트렌드",
    "title": "생년월일 타투",
    "keyword": "생년월일 타투"
  },
  {
    "id": 345,
    "category": "트렌드",
    "title": "별자리 별 추천 타투",
    "keyword": "별자리 별 추천 타투"
  },
  {
    "id": 346,
    "category": "트렌드",
    "title": "혈액형별 추천",
    "keyword": "혈액형별 추천"
  },
  {
    "id": 347,
    "category": "트렌드",
    "title": "MBTI별 타투 추천",
    "keyword": "MBTI별 타투 추천"
  },
  {
    "id": 348,
    "category": "트렌드",
    "title": "직업별 타투 추천",
    "keyword": "직업별 타투 추천"
  },
  {
    "id": 349,
    "category": "트렌드",
    "title": "BTS 멤버 타투 분석",
    "keyword": "BTS 멤버 타투 분석"
  },
  {
    "id": 350,
    "category": "트렌드",
    "title": "K-팝 아이돌 타투",
    "keyword": "K-팝 아이돌 타투"
  },
  {
    "id": 351,
    "category": "트렌드",
    "title": "할리우드 배우 타투",
    "keyword": "할리우드 배우 타투"
  },
  {
    "id": 352,
    "category": "트렌드",
    "title": "축구선수 타투",
    "keyword": "축구선수 타투"
  },
  {
    "id": 353,
    "category": "트렌드",
    "title": "K-드라마 속 타투",
    "keyword": "K-드라마 속 타투"
  },
  {
    "id": 354,
    "category": "트렌드",
    "title": "타투 가격 산정 기준",
    "keyword": "타투 가격 산정 기준"
  },
  {
    "id": 355,
    "category": "트렌드",
    "title": "타투 견적 받는 법",
    "keyword": "타투 견적 받는 법"
  },
  {
    "id": 356,
    "category": "트렌드",
    "title": "타투이스트 고르는 법",
    "keyword": "타투이스트 고르는 법"
  },
  {
    "id": 357,
    "category": "트렌드",
    "title": "타투샵 위생 체크리스트",
    "keyword": "타투샵 위생 체크리스트"
  },
  {
    "id": 358,
    "category": "트렌드",
    "title": "첫 상담 준비물",
    "keyword": "첫 상담 준비물"
  },
  {
    "id": 359,
    "category": "트렌드",
    "title": "도안 가져갈 때 매너",
    "keyword": "도안 가져갈 때 매너"
  },
  {
    "id": 360,
    "category": "트렌드",
    "title": "타투 후기 작성 팁",
    "keyword": "타투 후기 작성 팁"
  },
  {
    "id": 361,
    "category": "트렌드",
    "title": "여행지 타투 vs 한국 타투",
    "keyword": "여행지 타투 vs 한국 타투"
  },
  {
    "id": 362,
    "category": "트렌드",
    "title": "해외 유명 타투이스트",
    "keyword": "해외 유명 타투이스트"
  },
  {
    "id": 363,
    "category": "트렌드",
    "title": "한국 유명 타투이스트 TOP",
    "keyword": "한국 유명 타투이스트 TOP"
  },
  {
    "id": 364,
    "category": "트렌드",
    "title": "타투와 트렌드 컬러",
    "keyword": "타투와 트렌드 컬러"
  },
  {
    "id": 365,
    "category": "트렌드",
    "title": "지속 가능한 타투",
    "keyword": "지속 가능한 타투"
  }
] as const;

export const TOTAL_TOPICS = ENCYCLOPEDIA_TOPICS.length;
